"""Interface copy (Indonesian first, English second), taken from the JobFit v3 visual design.

Copy only: CV text, job postings and requirement text are never translated. Wording follows the
design's beta ("live") variant and the backend's real limits (5 MB upload, 200-character pasted
job description, 3 fit checks per session, the (MATCH + 0.5 x PARTIAL) / required formula).
"""
from __future__ import annotations

import streamlit as st

LANGS = ('id', 'en')

COPY: dict[str, dict[str, str]] = {
    'id': {
        # shell
        'brand.tag': 'Bukti, bukan tebakan.',
        'header.help': 'Bantuan',
        'header.delete': 'Hapus sesi',
        'nav.find': 'Cari Lowongan',
        'nav.check': 'Cek Lowongan',
        'nav.cv': 'CV siap ✓',
        'footer.left': 'JobFit · Cek CV berbasis bukti',
        'footer.right': 'Beta terbatas · {limit} cek kecocokan per sesi',
        'footer.link': 'Cara kerja & privasi',
        'back': '← Kembali',
        'cancel': 'Batal',
        'close': 'Tutup',
        'optional': 'Opsional',
        'dialog.ok': 'Mengerti',
        # status badges
        'badge.MATCH': 'Ada bukti',
        'badge.PARTIAL': 'Bukti sebagian',
        'badge.NO_MATCH': 'Belum ada bukti',
        'badge.UNVERIFIED': 'Belum bisa dipastikan',
        'badge.CONFLICT': 'Belum memenuhi syarat',
        # landing
        'landing.eyebrow': 'Untuk karier AI & data',
        'landing.h1': 'Cari lowongan.<br>Lihat buktinya di CV kamu.',
        'landing.lead': ('Judul lowongan tidak selalu menyebut level, padahal syaratnya bisa minta pengalaman 3 tahun. '
                         'JobFit menunjukkan syarat mana yang sudah ada buktinya di CV kamu, lengkap dengan kutipannya.'),
        'landing.cta': 'Unggah CV →',
        'landing.demo': 'Coba CV contoh',
        'landing.demo.note': 'CV contoh memakai hasil yang sudah tersimpan: instan, gratis, tanpa unggah.',
        'landing.privacy': 'Data pribadi dibersihkan dulu, dan kamu menyetujui teksnya sebelum dianalisis.',
        'landing.preview.eyebrow': 'Bukti, bukan tebakan',
        'landing.preview.note': 'Contoh hasil · CV contoh',
        'landing.preview.quoteLabel': 'Kutipan dari CV',
        'landing.preview.foot': 'Setiap hasil disertai kutipan yang bisa kamu cek sendiri.',
        'landing.how1.h': 'Cari lowongan yang relevan',
        'landing.how1.p': 'Mulai dari CV dan preferensi kamu.',
        'landing.how2.h': 'Cek kecocokan dengan bukti',
        'landing.how2.p': 'Setiap syarat lowongan dibandingkan dengan kutipan dari CV kamu.',
        'landing.how3.h': 'Perkuat CV dengan jujur',
        'landing.how3.p': 'Perjelas pengalaman yang memang kamu punya, tanpa menambah klaim.',
        # setup steps
        'steps.1': 'Unggah CV',
        'steps.2': 'Cek & setujui',
        'steps.3': 'CV siap',
        # upload
        'upload.h1': 'Mulai dari CV kamu',
        'upload.desc': 'Pilih file CV. Sebelum lanjut, kamu akan melihat dan menyetujui teks yang dipakai.',
        'upload.zone.h': 'Unggah CV',
        'upload.zone.formats': 'PDF, DOCX, TXT, atau MD · Maks. 5 MB · PDF maks. 10 halaman',
        'upload.file.label': 'Pilih file CV',
        'upload.notice': ('<strong>Kamu yang pegang kendali.</strong> File kamu diterima server JobFit hanya untuk '
                          'membaca teksnya. Data pribadi dibersihkan dulu, lalu kamu melihat dan menyetujui teksnya '
                          'sebelum ada yang dikirim ke layanan AI.'),
        'upload.small': 'Pembersihan otomatis punya batas. Cek lagi teksnya di langkah berikutnya.',
        'upload.download': 'Unduh CV contoh',
        'upload.demo': 'Coba CV contoh (tanpa unggah)',
        'upload.manual.summary': 'Tempel teks CV saja',
        'upload.manual.label': 'Teks CV',
        'upload.manual.hint': ('Untuk PDF hasil scan atau file yang tidak terbaca. Teks ini juga dibersihkan dari '
                               'data pribadi.'),
        'upload.manual.placeholder': ('PENGALAMAN KERJA\nTulis pengalaman, proyek, pendidikan, dan keterampilan '
                                      'kamu.'),
        'upload.manual.submit': 'Lanjut ke pengecekan',
        'upload.manual.empty': 'Tempel teks CV dulu.',
        # privacy review and consent
        'privacy.h1': 'Cek teks yang akan dianalisis',
        'privacy.desc': ('Ini teks persis yang akan dipakai setelah kamu setuju. Pastikan pengalaman kerjanya tetap '
                         'akurat.'),
        'privacy.tag': 'Data pribadi dibersihkan',
        'privacy.edit': 'Edit teks',
        'privacy.notice': ('Nama, kontak, ringkasan profil, dan bagian pribadi yang dikenali sudah dihapus atau '
                           'disamarkan. Pembersihan ini punya batas, jadi cek lagi apakah masih ada info sensitif.'),
        'privacy.what.summary': 'Apa saja yang dibersihkan?',
        'privacy.what.body': ('<strong>Dihapus:</strong> bagian identitas di atas CV, kontak, ringkasan (Summary, '
                              'Profile, Objective), minat, organisasi, dan referensi. <strong>Disamarkan:</strong> '
                              'email, nomor telepon, nomor identitas, tautan profil pribadi, alamat lengkap, nama kamu '
                              'yang muncul lagi di isi CV, dan nama orang setelah label seperti Supervisor atau '
                              'Mentor. <strong>Tetap dipakai:</strong> pengalaman kerja, proyek, pendidikan, '
                              'keterampilan, dan tanggal.'),
        'privacy.removed': 'Dihapus sebelum pratinjau: {items}',
        'privacy.label': 'Teks yang akan dianalisis',
        'privacy.source': ('Sumber: file atau teks yang kamu pilih. Kalau kamu mengedit teks, pembersihan dijalankan '
                           'lagi dan kamu perlu menyetujuinya ulang.'),
        'privacy.consent.strong': 'Saya sudah memeriksa teks di atas dan setuju teks ini dipakai untuk analisis.',
        'privacy.consent.small': ('Setelah kamu setuju, teks ini dikirim ke layanan AI melalui OpenRouter dengan '
                                  'pengaturan tanpa penyimpanan data (zero data retention). Hasilnya hanya ada '
                                  'selama sesi ini.'),
        'privacy.continue': 'Lanjutkan →',
        'privacy.replace': 'Ganti CV',
        # edit
        'edit.h1': 'Edit teks CV',
        'edit.desc': ('Setelah disimpan, teks dibersihkan lagi dan kamu perlu menyetujuinya ulang. Persetujuan dan '
                      'hasil sebelumnya tidak lagi berlaku setelah disimpan.'),
        'edit.label': 'Teks CV',
        'edit.back': 'Kembali tanpa menyimpan',
        'edit.submit': 'Simpan & cek lagi',
        'edit.unchanged': 'Belum ada perubahan untuk disimpan.',
        # processing
        'proc.sub': 'Jangan tutup halaman ini. Prosesnya bisa memakan waktu hingga beberapa menit.',
        'proc.honest': 'Daftar ini adalah tahapan prosesnya, bukan persentase. Tidak ada yang dijalankan dua kali.',
        'proc.elapsed': 'Berjalan {n} detik',
        'proc.elapsed.start': 'Baru dimulai…',
        'proc.back': 'Batalkan & kembali',
        'proc.parse.title': 'Menyiapkan CV kamu',
        'proc.parse.1': 'Memeriksa teks yang kamu setujui',
        'proc.parse.2': 'Membaca pengalaman dan keterampilan',
        'proc.parse.3': 'Menyiapkan profil pencarian',
        'proc.search.title': 'Mencari lowongan yang relevan…',
        'proc.search.1': 'Memahami isi CV kamu',
        'proc.search.2': 'Menelusuri database lowongan',
        'proc.search.3': 'Mengurutkan dari yang paling relevan',
        'proc.analyze.title': 'Mengecek kecocokan dengan lowongan ini…',
        'proc.analyze.1': 'Membaca syarat lowongan',
        'proc.analyze.2': 'Mencocokkan dan memeriksa ulang bukti di CV kamu',
        'proc.analyze.3': 'Menyusun yang sudah kuat dan yang perlu diperjelas',
        'proc.demo.title': 'Menganalisis lowongan…',
        'proc.demo.count': 'Selesai {done} dari {k} lowongan',
        'toast.cancelled': 'Proses dihentikan di layar ini. Permintaan yang sudah terkirim tetap diselesaikan di server.',
        # ready
        'ready.eyebrow': 'Persiapan selesai',
        'ready.h1': 'CV kamu siap. Mau mulai dari mana?',
        'ready.desc': 'Pilih salah satu. Kamu bisa pindah kapan saja lewat menu di atas.',
        'ready.summary.title': 'CV siap dipakai',
        'ready.summary.meta': '{n} baris teks · CV unggahan',
        'ready.review': 'Lihat teks CV',
        'ready.find.eyebrow': 'Belum punya lowongan incaran?',
        'ready.find.p': 'Cari lowongan AI dan data di database JobFit yang relevan dengan CV dan preferensi kamu.',
        'ready.check.eyebrow': 'Sudah punya lowongan incaran?',
        'ready.check.p': ('Tempel deskripsi lowongan dari mana saja, lalu lihat syarat mana yang sudah ada buktinya '
                          'di CV kamu.'),
        'ready.check.btn': 'Cek lowongan',
        'ready.skills.summary': 'Keterampilan yang terbaca dari CV kamu',
        'ready.skills.note': 'Dibaca oleh AI dari teks yang kamu setujui.',
        'ready.skills.empty': 'Belum ada keterampilan yang terbaca.',
        'ready.market': 'Lihat keterampilan teratas',
        # history (D-086)
        'history.check.strong': 'CV ini memuat seluruh riwayat kerja saya.',
        'history.check.small': ('Biarkan kosong kalau ada pekerjaan lama atau yang kurang relevan yang tidak kamu '
                                'cantumkan. Jawaban ini hanya berlaku untuk versi CV ini dan tidak mengubah cakupan '
                                'bukti.'),
        'history.locked': ('Jawaban ini dipakai untuk semua cek kecocokan dengan versi CV ini. Unggah atau edit CV '
                           'untuk mengubahnya.'),
        'history.on': 'Riwayat kerja: dikonfirmasi lengkap',
        'history.off': 'Riwayat kerja: belum dikonfirmasi lengkap',
        # find
        'find.h1': 'Cari lowongan yang relevan',
        'find.desc': 'Semua filter opsional. Tanpa filter, JobFit mencari di seluruh lowongan yang tersedia.',
        'find.panel.h2': 'Preferensi pencarian',
        'find.hint': 'Pencarian menampilkan lowongan relevan. Kecocokan dicek setelah kamu memilih satu lowongan.',
        'find.submit': 'Cari lowongan',
        'find.corpusNote': ('Di versi beta, pencarian berlaku sekali per sesi. Setelah itu, kamu bebas menyaring '
                            'hasilnya.'),
        'find.backToResults': 'Kembali ke hasil',
        'quota': 'Sisa {left} dari {limit} cek kecocokan',
        'quota.empty': 'Jatah cek kecocokan habis',
        'filter.role': 'Bidang peran',
        'filter.country': 'Negara',
        'filter.city': 'Kota',
        'filter.city.placeholder': 'Semua kota',
        'filter.experience': 'Pengalaman yang diminta',
        'filter.mode': 'Mode kerja',
        'filter.posted': 'Tayang dalam',
        'filter.more': 'Opsi lain',
        'filter.unknown.label': 'Tetap tampilkan lowongan yang datanya belum lengkap',
        'filter.unknown.small': ('Misalnya lowongan tanpa info lokasi atau tanggal tayang. Lowongan ini tidak '
                                 'disaring keluar hanya karena datanya kosong.'),
        'filter.any': 'Semua',
        'filter.anytime': 'Kapan saja',
        'filter.7': '7 hari terakhir',
        'filter.30': '30 hari terakhir',
        'country.ID': 'Indonesia', 'country.SG': 'Singapura', 'country.MY': 'Malaysia', 'country.PH': 'Filipina',
        'country.US': 'Amerika Serikat',
        'experience.entry': 'Entry level', 'experience.1-2y': '1–2 tahun', 'experience.3-4y': '3–4 tahun',
        'experience.5y+': '5+ tahun',
        'mode.onsite': 'On-site', 'mode.hybrid': 'Hybrid', 'mode.remote': 'Remote',
        'role.ai_ml_engineering': 'AI / ML Engineering', 'role.data_science': 'Data Science',
        'role.genai_llm': 'GenAI / LLM', 'role.software_ai': 'Software-AI',
        # results
        'results.h1': 'Lowongan yang relevan dengan CV kamu',
        'results.desc': ('Diurutkan dari yang paling relevan dengan CV dan filter kamu. Relevan belum tentu cocok: '
                         'pilih Cek kecocokan untuk melihat buktinya.'),
        'results.meta': 'Urutan: paling relevan dulu · tahap pencarian, belum ada skor',
        'results.changeSearch': 'Ubah pencarian',
        'results.h2': 'Hasil pencarian',
        'results.count': 'Menampilkan {x} dari {y} lowongan',
        'results.emptyFiltered.h': 'Tidak ada lowongan dengan filter ini',
        'results.emptyFiltered.p': 'Hasil pencarian kamu masih tersimpan. Hapus filter untuk melihatnya lagi.',
        'results.emptySearch.h': 'Belum ada lowongan yang ditemukan',
        'results.emptySearch.p': ('Belum ada lowongan dengan filter ini, dan filternya tidak dilonggarkan otomatis. '
                                  'CV kamu tetap siap dipakai; ubah filter atau coba Cek Lowongan.'),
        'results.foot': 'Hasil pencarian belum diberi skor. Skor hanya muncul setelah kamu cek kecocokan.',
        'refine.summary': 'Saring hasil ({n})',
        'refine.p': 'Hanya mengubah lowongan yang ditampilkan. Tidak ada pencarian atau cek kecocokan baru.',
        'refine.reset': 'Hapus filter',
        'job.location.none': 'Lokasi tidak dicantumkan',
        'job.mode.none': 'Mode kerja tidak dicantumkan',
        'job.experience': 'Pengalaman {x}',
        'job.experience.none': 'Pengalaman tidak dicantumkan',
        'job.role.none': 'Bidang tidak dicantumkan',
        'job.date': 'Tayang {n} hari lalu',
        'job.date.today': 'Tayang hari ini',
        'job.date.on': 'Tayang {date}',
        'job.date.none': 'Tanggal tidak dicantumkan',
        'job.missing': 'Sebagian info filter tidak ada di lowongan ini',
        'job.analyze': 'Cek kecocokan →',
        'job.viewResult': 'Lihat hasil cek →',
        'job.cachedNote': 'Sudah dicek',
        'job.apply': 'Lihat lowongan asli ↗',
        # check a job
        'check.h1': 'Cek lowongan yang kamu temukan',
        'check.desc': ('Tempel deskripsi lowongan lengkap, termasuk bagian syaratnya, supaya bisa dibandingkan dengan '
                       'bukti di CV kamu.'),
        'check.label': 'Deskripsi lowongan (wajib)',
        'check.hint': ('Deskripsi ini hanya dipakai di sesi ini, diperlakukan sebagai data (bukan instruksi), dan '
                       'tidak ditambahkan ke database lowongan JobFit.'),
        'check.error': ('Deskripsinya terlalu pendek. Tempel deskripsi lengkap, minimal 200 karakter, termasuk syarat '
                        'pekerjaannya.'),
        'check.foot': 'Kalau syarat lowongan tidak terbaca jelas, JobFit menahan hasilnya dan tidak memberi skor asal.',
        'pasted.title': 'Lowongan yang kamu tempel',
        'pasted.company': 'Deskripsi dari kamu · sesi ini',
        # analysis
        'page.results': 'Lowongan Relevan',
        'page.analysis': 'Hasil Cek Kecocokan',
        'analysis.back.check': '← Kembali ke deskripsi',
        'analysis.back.results': '← Kembali ke hasil',
        'coverage.label': 'Cakupan bukti CV',
        'coverage.h2': 'Cakupan Bukti CV',
        'coverage.disclaimer': ('Mengukur seberapa banyak syarat wajib yang ada buktinya di CV kamu. Bukan peluang '
                                'diterima kerja.'),
        'coverage.counts': '{a} ada bukti · {b} bukti sebagian · {c} belum ada bukti',
        'coverage.basis': 'Dihitung dari {n} syarat wajib di lowongan ini.',
        'coverage.provisional': 'Skor sementara: sebagian syarat masih perlu dicek.',
        'hold.h': 'Hasil ditahan: tidak ada skor',
        'hold.why': 'Kenapa ditahan:',
        'req.flagged': 'Syarat ini yang membuat skornya ditahan: strukturnya perlu dicek dulu.',
        'reason.protected': 'Syarat pengalaman, level, atau pendidikan ini perlu dicek dulu: {items}',
        'reason.over20': 'Lebih dari 20% syarat wajib yang dinilai perlu dicek, jadi skor tidak bisa dipastikan.',
        'reason.notjudged': 'Syarat wajib ini belum sempat dinilai: {items}',
        'reason.incomplete': 'Deskripsi lowongan terlihat tidak lengkap. Tempel deskripsi lengkapnya lewat Cek Lowongan.',
        'reason.norequired': 'Tidak ada syarat wajib yang cukup jelas untuk dihitung.',
        'reason.matching': 'Pencocokan bukti dengan CV belum selesai ({code}). Coba lagi nanti; tidak ada skor yang dibuat.',
        'reason.extraction': 'Syarat lowongan belum bisa dibaca ({code}). Tidak ada skor yang dibuat.',
        'reason.envelope': ('Daftar syarat lowongan ini lebih besar dari batas analisis beta. Tidak ada yang dipotong '
                            'dan tidak ada pencocokan yang dijalankan.'),
        'reason.excluded': 'Beberapa syarat perlu dicek dan tidak dihitung di skor: {items}',
        'reason.unknownimportance': '{n} syarat belum jelas wajib atau nilai tambah.',
        'provisional.why': 'Kenapa skornya sementara:',
        'hold.note': ('Aturan kejujuran JobFit: kalau ada syarat yang belum bisa dinilai dengan pasti, skor ditahan, '
                      'bukan dikarang. Bukti per syarat di bawah tetap bisa kamu baca.'),
        'hold.p': 'Lowongan ini belum bisa dianalisis penuh, jadi tidak ada skor yang ditampilkan (tidak ada yang dikarang).',
        'req.h2': 'Bukti untuk setiap syarat',
        'req.meta': 'Kutipan dari CV yang kamu setujui',
        'req.required': 'Syarat wajib',
        'req.preferred': 'Nilai tambah · tidak dihitung di skor',
        'req.other': 'Syarat lain · tidak dihitung di skor',
        'req.quoteLabel': 'Kutipan dari CV kamu',
        'reason.match': 'Kutipan ini menunjukkan pengalaman yang sesuai dengan syarat ini.',
        'reason.partial': 'Ada informasi yang terkait, tapi konteks atau kontribusi kamu belum cukup jelas.',
        'reason.none': 'JobFit belum menemukan buktinya di CV ini. Bukan berarti kamu tidak punya keterampilan ini.',
        'reason.unchecked': 'Syarat ini belum dicek, jadi tidak dihitung.',
        'reason.unverified': 'Belum bisa dipastikan dari CV ini. Ini bukan gap dan tidak dihitung sebagai kekurangan.',
        'reason.conflict': 'Bertentangan dengan riwayat kerja yang kamu konfirmasi lengkap.',
        'excluded': '{n} syarat perlu dicek dan ditampilkan, tetapi tidak dihitung di skor.',
        'soft': 'Soft skill (ditampilkan terpisah, tidak masuk persentase): {a} ada bukti, {b} sebagian, dari {n}.',
        'exp.h3': 'Pengalaman yang diminta',
        'exp.conflict': ('Ini soal latar belakang, bukan cara menulis. Mengubah kalimat di CV tidak menambah lama '
                         'pengalaman.'),
        'unverified.h3': 'Belum bisa dipastikan dari CV ini',
        'unverified.p': ('Syarat lama pengalaman, lokasi, atau izin kerja yang tidak bisa dipastikan dari CV ini. '
                         'Bukan gap: hal ini tidak dibandingkan dengan latar belakang kamu.'),
        'calc.summary': 'Bagaimana skor ini dihitung?',
        'calc.body': ('Setiap syarat wajib yang ada buktinya bernilai 1, dan bukti sebagian bernilai 0,5. Totalnya '
                      'dibagi {n} syarat wajib yang dinilai. Nilai tambah dan syarat yang perlu dicek tidak '
                      'dihitung.'),
        'calc.note': ('Syarat dibaca dan dicocokkan oleh model AI, lalu setiap kutipan dicek ulang agar persis sama '
                      'dengan teks CV kamu.'),
        'side.strong.h3': 'Sudah ada buktinya',
        'side.strong.empty': 'Belum ada syarat dengan bukti yang kuat.',
        'side.gaps.h3': 'Perlu diperjelas atau dilengkapi',
        'side.gaps.empty': 'Semua syarat wajib sudah ada buktinya.',
        'side.gaps.note': 'Belum ada bukti belum tentu belum mampu.',
        'side.next.h3': 'Langkah berikutnya',
        'side.next.p': 'Perjelas pengalaman yang memang kamu punya.',
        'side.next.btn': 'Perkuat CV',
        'analysis.empty.h': 'Pilih lowongan dulu',
        'analysis.empty.p': 'Cek kecocokan dimulai dari lowongan yang kamu pilih.',
        # coach
        'page.coach': 'Perkuat CV',
        'coach.back': '← Kembali ke hasil cek',
        'coach.h1': 'Perjelas bukti. Tetap jujur.',
        'coach.desc': ('Saran untuk {job}. Disusun hanya dari bukti CV dan jawaban kamu. Tidak ada yang dikarang, dan '
                       'jawaban tidak mengubah skor; skor baru berubah setelah kamu memperbarui dan mengunggah ulang '
                       'CV.'),
        'coach.partial.h2': 'Perjelas bukti yang sudah ada',
        'coach.item.asks': 'Lowongan ini meminta',
        'coach.item.current': 'Bukti di CV kamu saat ini',
        'coach.partial.empty': 'Tidak ada bukti sebagian yang perlu diperjelas.',
        'coach.missing.h2': 'Mungkin belum tertulis di CV',
        'coach.missing.p': 'Belum ada bukti bukan berarti belum pernah. Jawab dengan jujur dulu.',
        'coach.missing.q': 'Apakah kamu pernah melakukan ini?',
        'coach.missing.empty': 'Tidak ada syarat wajib yang belum ada buktinya.',
        'coach.yes': 'Ya, pernah',
        'coach.no': 'Belum pernah',
        'coach.no.notice': ('Tidak apa-apa. Jangan tambahkan klaim ini ke CV. Kalau ingin menutup gap ini, cari proyek '
                            'atau pengalaman yang relevan, lalu catat kontribusi yang benar-benar kamu lakukan.'),
        'coach.changeAnswer': 'Ubah jawaban',
        'coach.form.intro': 'Isi dua pertanyaan wajib (*). Alat dan hasil boleh dikosongkan kalau tidak ada.',
        'coach.q.what_when': 'Di mana dan kapan kamu melakukannya? *',
        'coach.q.what_when.hint': 'Nama proyek atau pekerjaan, dan waktunya.',
        'coach.q.own_part': 'Bagian mana yang kamu kerjakan sendiri? *',
        'coach.q.own_part.hint': 'Tulis yang benar-benar kamu lakukan, bukan kerja tim secara umum.',
        'coach.q.tools': 'Alat atau metode apa yang kamu pakai?',
        'coach.q.tools.hint': 'Tulis nama yang tepat. Jangan menebak.',
        'coach.q.result': 'Apa hasilnya? Ada angka yang bisa kamu pertanggungjawabkan?',
        'coach.q.result.hint': 'Hasil yang nyata. Kosongkan kalau tidak ada.',
        'coach.form.error': 'Lengkapi dulu: {list}.',
        'coach.submit': 'Susun draf dari jawaban',
        'coach.true.h2': 'Gap yang memang ada (fakta, bukan cara menulis)',
        'coach.true.note': 'Tidak ada saran penulisan untuk hal ini.',
        'coach.unverified.h2': 'Belum bisa dipastikan dari CV ini',
        'coach.nothing': 'Tidak ada yang perlu diperkuat dari syarat wajib lowongan ini.',
        'coach.ideas': 'Ide yang bisa kamu lakukan',
        'draft.h4': 'Draf dari jawaban kamu',
        'draft.note': ('Cek lagi kebenarannya sebelum dimasukkan ke CV. JobFit tidak menambahkan alat, angka, atau '
                       'pengalaman apa pun.'),
        'draft.editLabel': 'Edit draf',
        'draft.save': 'Simpan',
        'draft.accept': 'Terima',
        'draft.edit': 'Edit',
        'draft.reject': 'Tolak',
        'draft.copy': 'Salin draf (ikon salin di kanan atas kotak)',
        'draft.status.accepted': 'Diterima',
        'draft.status.rejected': 'Ditolak',
        'draft.status.edited': 'Kamu edit',
        'draft.status.review': 'Perlu dicek',
        'draft.facts': 'Jawaban yang dipakai',
        'dialog.accept.title': 'Sudah cek kebenarannya?',
        'dialog.accept.body': ('Pastikan setiap detail benar dan bisa kamu jelaskan saat wawancara. Draf hanya disimpan '
                               'di sesi ini. CV asli dan skor tidak berubah.'),
        'dialog.accept.yes': 'Ya, simpan draf',
        'dialog.accept.no': 'Cek lagi',
        'toast.accepted': 'Draf disimpan di sesi ini. CV asli kamu belum berubah.',
        'toast.rejected': 'Draf ditolak. Jawaban kamu masih ada kalau ingin diperbaiki.',
        # market
        'market.back': '← Kembali',
        'market.eyebrow': 'Wawasan tambahan',
        'market.h1': 'Keterampilan yang paling sering diminta',
        'market.desc': 'Dihitung dari lowongan di database JobFit. Bukan gambaran seluruh pasar kerja.',
        'market.role': 'Bidang peran',
        'market.all': 'Semua bidang',
        'market.row': '{n} dari {total} lowongan',
        'market.lead': ('Di {total} lowongan yang bisa dicari, {skill} muncul di {n} lowongan ({pct}%). Hitungan diambil '
                        'dari daftar keterampilan tiap lowongan, bukan dari seluruh pasar kerja.'),
        'market.empty': 'Tidak ada lowongan untuk filter ini.',
        'market.source': 'Sumber: {source}',
        # saved synthetic demo
        'demo.eyebrow': 'CV contoh · hasil tersimpan',
        'demo.h1': 'Coba JobFit dengan CV contoh',
        'demo.desc': ('CV sintetis, bukan orang sungguhan. Mode bawaan memakai hasil yang sudah tersimpan: instan, '
                      'gratis, dan tanpa unggah.'),
        'demo.cv': 'Pilih CV contoh',
        'demo.cv.option': '{id} (sintetis): {jobs}',
        'demo.cv.nojobs': 'tanpa riwayat kerja',
        'demo.seniority': 'Turunkan lowongan yang meminta 3+ tahun',
        'demo.seniority.help': 'Aturan untuk awal karier. Lowongan hanya diturunkan, tidak dihapus.',
        'demo.live': 'Analisis live (memanggil model berbayar)',
        'demo.live.help': ('Mati: demo dengan hasil tersimpan, instan dan gratis, hanya daftar tanpa filter. Hidup: '
                           'menjalankan pipeline sungguhan sekarang (khusus pengembangan).'),
        'demo.filters': 'Filter (hanya untuk analisis live)',
        'demo.unknown': 'Tetap tampilkan lowongan yang datanya belum lengkap',
        'demo.unknown.help': 'Data kosong tidak sama dengan cocok. Lowongan ini ditampilkan di blok tersendiri.',
        'demo.summary': 'Ringkasan pembacaan CV (cek sebelum analisis)',
        'demo.summary.location': ('Saran lokasi: {loc} (hanya saran; tidak pernah dipakai sebagai lokasi kamu yang '
                                  'terkonfirmasi).'),
        'demo.summary.none': 'tidak ditemukan',
        'demo.summary.sections': 'Bagian yang ditemukan: {sections}',
        'demo.summary.unavailable': 'Ringkasan tidak tersedia ({status}).',
        'demo.col.title': 'Jabatan', 'demo.col.org': 'Organisasi', 'demo.col.start': 'Mulai', 'demo.col.end': 'Selesai',
        'demo.present': 'sekarang',
        'demo.text': 'Lihat teks CV contoh',
        'demo.run': 'Cari lowongan yang cocok →',
        'demo.saved': 'Demo dengan hasil tersimpan: dihitung sebelumnya untuk CV sintetis dan konfigurasi ini.',
        'demo.analyzed': ('{k} kandidat dari pencarian dianalisis (pencarian tahap 1, lalu pencocokan bukti). '
                          '{rule}'),
        'demo.rule.on': '{n} lowongan diturunkan oleh aturan 3+ tahun.',
        'demo.rule.off': 'Aturan 3+ tahun dimatikan.',
        'demo.matches': 'Cocok ({n})',
        'demo.conflicts': 'Kemungkinan konflik ({n})',
        'demo.conflicts.p': ('Lowongan ini meminta lebih banyak tahun daripada seluruh riwayat kerja yang '
                             'terkonfirmasi. Skornya tidak berubah; lowongan ini ditaruh setelah lowongan lain yang '
                             'sudah dinilai.'),
        'demo.unscored': 'Belum bisa dianalisis penuh ({n})',
        'demo.suggest.h2': 'Saran CV',
        'demo.suggest.btn': 'Tampilkan saran dari hasil ini',
        'demo.suggest.none': 'Tidak ada saran: tidak ada syarat wajib yang sebagian atau belum ada buktinya.',
        'demo.suggest.asked': 'diminta oleh {n} lowongan yang dianalisis',
        'demo.suggest.quote': 'Dari CV kamu: {q}',
        'demo.coach.pick': 'Perkuat CV untuk satu lowongan demo',
        'demo.versions': 'Versi: {v}',
        'demo.failed': 'Analisis berhenti ({error}). Tidak ada skor yang dikarang.',
        'card.of': '{a} ada bukti, {b} sebagian, dari {n} syarat wajib',
        'card.evidence': 'Bukti per syarat',
        'card.posting': 'Teks lowongan',
        'card.posting.load': 'Muat teks lowongan',
        'card.posting.error': 'Teks lowongan tidak bisa dimuat ({err}).',
        'card.conflict': 'Kemungkinan konflik: {msg}',
        'card.status.final': 'Skor', 'card.status.provisional': 'Skor sementara',
        'card.status.on_hold': 'Belum dianalisis penuh', 'card.status.no_score': 'Tanpa skor',
        'col.requirement': 'Syarat', 'col.type': 'Jenis', 'col.result': 'Hasil', 'col.quote': 'Kutipan CV',
        'feedback.reason': 'Alasan',
        'feedback.useful': 'Berguna', 'feedback.not': 'Tidak berguna',
        'feedback.thanks': 'Terima kasih, masukan disimpan (hanya penilaian dan alasan).',
        'reason.relevant': 'Relevan', 'reason.not_relevant_role': 'Peran tidak sesuai',
        'reason.too_senior': 'Terlalu senior', 'reason.wrong_evidence': 'Buktinya salah',
        'reason.missing_requirement': 'Ada syarat yang terlewat', 'reason.other': 'Lainnya',
        # dialogs
        'dialog.help.title': 'Cara membaca hasil JobFit',
        'dialog.help.p1': ('<strong>Cari Lowongan</strong> (Find Jobs) menampilkan lowongan yang relevan dengan CV '
                           'kamu. <strong>Cek Kecocokan</strong> (Analyze Fit) membandingkan setiap syarat lowongan '
                           'dengan kutipan dari CV kamu.'),
        'dialog.help.p2': ('<strong>Cakupan Bukti CV</strong> (CV Evidence Coverage) menunjukkan seberapa banyak syarat '
                           'wajib yang ada buktinya. Ini bukan peluang diterima kerja dan bukan skor ATS.'),
        'dialog.help.p3': ('Belum ada bukti di CV bukan berarti kamu tidak punya keterampilannya. Hal yang belum bisa '
                           'dipastikan ditandai <strong>Belum bisa dipastikan</strong>.'),
        'dialog.help.small': ('Beta terbatas: {limit} cek kecocokan per sesi. File kamu diproses sementara di server, '
                              'dibersihkan dari data pribadi, dan baru dikirim ke layanan AI melalui OpenRouter '
                              'setelah kamu setuju. Data sesi dihapus saat kamu menekan Hapus sesi, sekitar 2 menit '
                              'setelah halaman ditutup, setelah 30 menit tanpa aktivitas, atau setelah 2 jam.'),
        'dialog.delete.title': 'Hentikan & hapus sesi?',
        'dialog.delete.body': ('Teks CV, persetujuan, hasil cek, deskripsi lowongan, dan draf di sesi ini akan dihapus '
                               'di server. Proses yang sedang berjalan juga dihentikan.'),
        'dialog.delete.small': 'Tindakan ini tidak bisa dibatalkan. File asli di perangkat kamu tidak ikut terhapus.',
        'dialog.delete.yes': 'Hentikan & hapus sesi',
        'dialog.replace.title': 'Ganti CV ini?',
        'dialog.replace.body': ('Persetujuan, hasil, jawaban riwayat kerja, dan draf untuk CV ini akan dihapus. Jatah cek '
                                'kecocokan yang sudah terpakai tetap terhitung.'),
        'limit.title': 'Jatah cek kecocokan habis',
        'limit.body': 'Kamu sudah memakai {limit} cek kecocokan di sesi ini. Hasil yang sudah ada tetap bisa dibuka.',
        # terminal and errors
        'deleted.h1': 'Sesi sudah dihapus',
        'deleted.desc': 'Data sesi kamu sudah dihapus di server.',
        'expired.h1': 'Sesi kamu sudah berakhir',
        'expired.desc': ('Sesi berakhir karena tidak ada aktivitas atau halaman terlalu lama ditinggal, dan datanya '
                         'sudah dihapus di server. Sesi baru yang kosong sudah dimulai.'),
        'terminal.h2': 'Kendali tetap di tangan kamu.',
        'terminal.p.deleted': 'Kamu bisa mulai lagi kapan saja dengan CV yang sama atau CV baru.',
        'terminal.p.expired': 'Sesi lama tidak dipulihkan otomatis. Unggah CV lagi dan setujui ulang teksnya.',
        'terminal.btn': 'Kembali ke beranda',
        'api.down.h1': 'JobFit belum bisa dihubungi',
        'api.down.p': ('API JobFit di {url} belum bisa dihubungi. Mungkin masih dinyalakan. Tunggu beberapa detik, '
                       'lalu tekan Coba lagi. ({err})'),
        'api.retry': 'Coba lagi',
        'api.outdated': ('<strong>API yang tersambung ({url}) versi lama.</strong> API ini belum memakai pembersihan '
                         'D-104: nama dan header kontak tidak dihapus, dan edit teks tidak didukung. Jalankan UI '
                         'dengan API terbaru (lihat runbook owner-local), lalu muat ulang halaman ini.'),
        'err.not_found': ('Langkah ini tidak dikenal oleh API di {url} (Not Found). API itu kemungkinan versi lama; '
                          'jalankan API dari kode terbaru.'),
        'err.connection': ('Koneksi bermasalah: tekan tombolnya lagi untuk mengulang permintaan yang sama (tidak akan '
                           'dijalankan dua kali).'),
        'err.stopped': 'Proses berhenti ({error}). Tidak ada hasil yang dikarang.',
        'err.code.allowance_exhausted': 'Jatah sesi ini untuk langkah ini sudah habis.',
        'err.code.busy': 'Permintaan lain sedang diproses. Coba lagi sebentar lagi.',
        'err.code.consent_required': 'Persetujuan untuk teks CV ini belum ada atau sudah tidak berlaku.',
        'err.code.search_required': 'Jalankan Cari Lowongan dulu.',
        'err.code.parse_required': 'CV belum disiapkan. Setujui teksnya dan lanjutkan dulu.',
        'err.code.input_too_large': 'Teksnya terlalu panjang untuk dianalisis di beta ini.',
        'err.code.ticket_required': 'Analisis live belum tersedia untuk sesi ini.',
        'err.code.unavailable': 'Analisis AI sedang tidak tersedia. Silakan coba lagi nanti. Tidak ada skor yang dibuat.',
        'err.code.production_retrieval_unavailable': 'Pencarian sedang tidak tersedia. CV kamu tetap siap dipakai.',
    },
    'en': {
        'brand.tag': 'Evidence, not guesswork.',
        'header.help': 'Help',
        'header.delete': 'Delete session',
        'nav.find': 'Find Jobs',
        'nav.check': 'Check a Job',
        'nav.cv': 'CV ready ✓',
        'footer.left': 'JobFit · Evidence-first career tools',
        'footer.right': 'Limited beta · {limit} fit checks per session',
        'footer.link': 'How it works & privacy',
        'back': '← Back',
        'cancel': 'Cancel',
        'close': 'Close',
        'optional': 'Optional',
        'dialog.ok': 'Got it',
        'badge.MATCH': 'Evidence found',
        'badge.PARTIAL': 'Partial evidence',
        'badge.NO_MATCH': 'No evidence yet',
        'badge.UNVERIFIED': "Can't confirm yet",
        'badge.CONFLICT': 'Requirement not met',
        'landing.eyebrow': 'For AI & data careers',
        'landing.h1': 'Find the jobs.<br>See the proof in your CV.',
        'landing.lead': ("Job titles don't always show the level, yet the requirements may ask for 3+ years. JobFit "
                         'shows which requirements your CV already backs up, quoting the exact lines.'),
        'landing.cta': 'Upload CV →',
        'landing.demo': 'Try a sample CV',
        'landing.demo.note': 'The sample CV uses saved results: instant, free, no upload.',
        'landing.privacy': 'Personal details are removed first, and you approve the text before any analysis.',
        'landing.preview.eyebrow': 'Evidence, not guesswork',
        'landing.preview.note': 'Sample result · Sample CV',
        'landing.preview.quoteLabel': 'Quoted from the CV',
        'landing.preview.foot': 'Every result comes with a quote you can check yourself.',
        'landing.how1.h': 'Find relevant jobs',
        'landing.how1.p': 'Start from your CV and preferences.',
        'landing.how2.h': 'Check fit with evidence',
        'landing.how2.p': 'Each requirement is compared with quotes from your CV.',
        'landing.how3.h': 'Strengthen your CV honestly',
        'landing.how3.p': 'Clarify experience you really have, with no new claims.',
        'steps.1': 'Upload CV',
        'steps.2': 'Review & agree',
        'steps.3': 'CV ready',
        'upload.h1': 'Start with your CV',
        'upload.desc': "Choose your CV file. Before anything else, you'll see and approve the text we'll use.",
        'upload.zone.h': 'Upload CV',
        'upload.zone.formats': 'PDF, DOCX, TXT or MD · Max 5 MB · PDF up to 10 pages',
        'upload.file.label': 'Choose CV file',
        'upload.notice': ("<strong>You stay in control.</strong> JobFit's server receives your file only to read its "
                          'text. Personal details are removed first, and you see and approve the text before anything '
                          'goes to an AI service.'),
        'upload.small': 'Automatic cleanup has limits. Check the text again in the next step.',
        'upload.download': 'Download sample CV',
        'upload.demo': 'Try a sample CV (no upload)',
        'upload.manual.summary': 'Paste CV text instead',
        'upload.manual.label': 'CV text',
        'upload.manual.hint': "For scanned PDFs or files that can't be read. This text is also cleaned of personal details.",
        'upload.manual.placeholder': 'WORK EXPERIENCE\nList your experience, projects, education and skills.',
        'upload.manual.submit': 'Continue to review',
        'upload.manual.empty': 'Paste your CV text first.',
        'privacy.h1': "Check the text we'll analyze",
        'privacy.desc': ('This is the exact text that will be used once you agree. Make sure your work experience '
                         'still reads correctly.'),
        'privacy.tag': 'Personal details removed',
        'privacy.edit': 'Edit text',
        'privacy.notice': ('Your name, contact details, profile summary and other personal sections we recognize have '
                           "been removed or hidden. This cleanup has limits, so check for anything sensitive that's "
                           'left.'),
        'privacy.what.summary': 'What gets removed?',
        'privacy.what.body': ('<strong>Removed:</strong> the identity header, contact details, summary (Summary, '
                              'Profile, Objective), interests, organizations and references. <strong>Hidden:</strong> '
                              'emails, phone numbers, ID numbers, personal profile links, full addresses, your name if '
                              "it appears again in the CV, and people's names after labels such as Supervisor or "
                              'Mentor. <strong>Kept:</strong> work experience, projects, education, skills and dates.'),
        'privacy.removed': 'Removed before preview: {items}',
        'privacy.label': 'Text to be analyzed',
        'privacy.source': ("Source: the file or text you provided. If you edit the text, cleanup runs again and you'll "
                           'need to approve it again.'),
        'privacy.consent.strong': "I've checked the text above and agree to it being used for analysis.",
        'privacy.consent.small': ('Once you agree, this text is sent to AI services through OpenRouter with '
                                  'zero-data-retention settings. Results exist only for this session.'),
        'privacy.continue': 'Continue →',
        'privacy.replace': 'Replace CV',
        'edit.h1': 'Edit CV text',
        'edit.desc': ("When you save, the text is cleaned again and you'll need to approve it again. Your earlier "
                      'approval and results no longer apply after saving.'),
        'edit.label': 'CV text',
        'edit.back': 'Back without saving',
        'edit.submit': 'Save & review',
        'edit.unchanged': 'There are no changes to save yet.',
        'proc.sub': 'Keep this page open. This can take up to a few minutes.',
        'proc.honest': 'These are the stages of the process, not a percentage. Nothing runs twice.',
        'proc.elapsed': 'Running for {n} s',
        'proc.elapsed.start': 'Just started…',
        'proc.back': 'Cancel & go back',
        'proc.parse.title': 'Preparing your CV',
        'proc.parse.1': 'Checking the text you approved',
        'proc.parse.2': 'Reading experience and skills',
        'proc.parse.3': 'Preparing your search profile',
        'proc.search.title': 'Finding relevant jobs…',
        'proc.search.1': 'Understanding your CV',
        'proc.search.2': 'Searching the job database',
        'proc.search.3': 'Sorting by relevance',
        'proc.analyze.title': 'Checking your fit for this job…',
        'proc.analyze.1': 'Reading the job requirements',
        'proc.analyze.2': 'Matching and re-checking evidence in your CV',
        'proc.analyze.3': 'Summarizing strengths and gaps',
        'proc.demo.title': 'Analyzing jobs…',
        'proc.demo.count': 'Analyzed {done} of {k} jobs',
        'toast.cancelled': 'Stopped on this screen. A request already sent will still finish on the server.',
        'ready.eyebrow': 'Setup complete',
        'ready.h1': 'Your CV is ready. Where do you want to start?',
        'ready.desc': 'Pick one. You can switch anytime from the menu above.',
        'ready.summary.title': 'CV ready to use',
        'ready.summary.meta': '{n} lines of text · Uploaded CV',
        'ready.review': 'View CV text',
        'ready.find.eyebrow': 'No job in mind yet?',
        'ready.find.p': "Search JobFit's job database for AI and data roles that match your CV and preferences.",
        'ready.check.eyebrow': 'Already found a job?',
        'ready.check.p': 'Paste a job description from anywhere and see which requirements your CV already backs up.',
        'ready.check.btn': 'Check a job',
        'ready.skills.summary': 'Skills found in your CV',
        'ready.skills.note': 'Read by AI from the text you approved.',
        'ready.skills.empty': 'No skills detected yet.',
        'ready.market': 'See top skills',
        'history.check.strong': 'This CV lists my complete work history.',
        'history.check.small': ('Leave unticked if you left out older or less relevant jobs. This applies to this '
                                'version of your CV only and never changes the evidence coverage.'),
        'history.locked': ('This answer applies to every fit check for this version of your CV. Upload or edit your '
                           'CV to change it.'),
        'history.on': 'Work history: confirmed complete',
        'history.off': 'Work history: not confirmed complete',
        'find.h1': 'Find relevant jobs',
        'find.desc': 'All filters are optional. Without them, JobFit searches every available job.',
        'find.panel.h2': 'Search preferences',
        'find.hint': 'Search shows relevant jobs. Fit is checked after you pick one.',
        'find.submit': 'Find jobs',
        'find.corpusNote': 'In the beta, you can search once per session. After that, filter the results as you like.',
        'find.backToResults': 'Back to results',
        'quota': '{left} of {limit} fit checks left',
        'quota.empty': 'No fit checks left',
        'filter.role': 'Role family',
        'filter.country': 'Country',
        'filter.city': 'City',
        'filter.city.placeholder': 'All cities',
        'filter.experience': 'Experience required',
        'filter.mode': 'Work mode',
        'filter.posted': 'Posted within',
        'filter.more': 'More options',
        'filter.unknown.label': 'Include jobs with missing details',
        'filter.unknown.small': ("For example, jobs with no location or posting date. They won't be filtered out just "
                                 'because a detail is missing.'),
        'filter.any': 'Any',
        'filter.anytime': 'Any time',
        'filter.7': 'Last 7 days',
        'filter.30': 'Last 30 days',
        'country.ID': 'Indonesia', 'country.SG': 'Singapore', 'country.MY': 'Malaysia', 'country.PH': 'Philippines',
        'country.US': 'United States',
        'experience.entry': 'Entry level', 'experience.1-2y': '1–2 years', 'experience.3-4y': '3–4 years',
        'experience.5y+': '5+ years',
        'mode.onsite': 'On-site', 'mode.hybrid': 'Hybrid', 'mode.remote': 'Remote',
        'role.ai_ml_engineering': 'AI / ML Engineering', 'role.data_science': 'Data Science',
        'role.genai_llm': 'GenAI / LLM', 'role.software_ai': 'Software-AI',
        'results.h1': 'Jobs relevant to your CV',
        'results.desc': ("Sorted by relevance to your CV and filters. Relevant doesn't mean a fit yet: choose Analyze "
                         'fit to see the evidence.'),
        'results.meta': 'Order: most relevant first · search stage, no score yet',
        'results.changeSearch': 'Change search',
        'results.h2': 'Search results',
        'results.count': 'Showing {x} of {y} jobs',
        'results.emptyFiltered.h': 'No jobs match these filters',
        'results.emptyFiltered.p': 'Your search results are still here. Clear the filters to see them again.',
        'results.emptySearch.h': 'No jobs found',
        'results.emptySearch.p': ('No jobs match these filters, and nothing was widened automatically. Your CV is still '
                                  'ready; change the filters or try Check a Job.'),
        'results.foot': 'Search results have no score. A score appears only after you analyze fit.',
        'refine.summary': 'Filter results ({n})',
        'refine.p': 'Only changes which jobs are shown. No new search or fit check is run.',
        'refine.reset': 'Clear filters',
        'job.location.none': 'Location not listed',
        'job.mode.none': 'Work mode not listed',
        'job.experience': '{x} experience',
        'job.experience.none': 'Experience not listed',
        'job.role.none': 'Role not listed',
        'job.date': 'Posted {n} days ago',
        'job.date.today': 'Posted today',
        'job.date.on': 'Posted {date}',
        'job.date.none': 'Date not listed',
        'job.missing': 'Some filter details are missing in this posting',
        'job.analyze': 'Analyze fit →',
        'job.viewResult': 'View fit result →',
        'job.cachedNote': 'Already checked',
        'job.apply': 'View original posting ↗',
        'check.h1': 'Check a job you found',
        'check.desc': ('Paste the full job description, including the requirements, so it can be compared with the '
                       'evidence in your CV.'),
        'check.label': 'Job description (required)',
        'check.hint': ("Used in this session only, treated as data (never as instructions), and never added to "
                       "JobFit's job database."),
        'check.error': "That's too short. Paste the full job description, at least 200 characters, including the requirements.",
        'check.foot': "If the requirements can't be read clearly, JobFit holds the result instead of guessing a score.",
        'pasted.title': 'Job you pasted',
        'pasted.company': 'Your job description · this session',
        'page.results': 'Relevant Jobs',
        'page.analysis': 'Fit result',
        'analysis.back.check': '← Back to description',
        'analysis.back.results': '← Back to results',
        'coverage.label': 'CV evidence coverage',
        'coverage.h2': 'CV Evidence Coverage',
        'coverage.disclaimer': ("Measures how many required items your CV has evidence for. It's not your chance of "
                                'getting hired.'),
        'coverage.counts': '{a} with evidence · {b} partial · {c} no evidence yet',
        'coverage.basis': 'Based on {n} required items in this job.',
        'coverage.provisional': 'Provisional score: some requirements still need checking.',
        'hold.h': 'Result on hold: no score',
        'hold.why': 'Why it is on hold:',
        'req.flagged': 'This requirement is why the score is on hold: its structure needs checking first.',
        'reason.protected': 'This experience, level or education requirement needs checking first: {items}',
        'reason.over20': 'More than 20% of the scored required items need checking, so the score cannot be confirmed.',
        'reason.notjudged': 'These required items were not judged yet: {items}',
        'reason.incomplete': 'The job description looks incomplete. Paste the full description in Check a Job.',
        'reason.norequired': 'No required items are clear enough to compute a score.',
        'reason.matching': 'Matching the evidence with your CV did not finish ({code}). Try again later; no score was created.',
        'reason.extraction': 'The job requirements could not be read ({code}). No score was created.',
        'reason.envelope': ('The requirement list of this job is larger than the beta analysis limit. Nothing was cut and '
                            'no matching was run.'),
        'reason.excluded': 'Some requirements need checking and are not counted in the score: {items}',
        'reason.unknownimportance': '{n} requirement(s) not clearly required or nice to have.',
        'provisional.why': 'Why the score is provisional:',
        'hold.note': ("JobFit's honesty rule: when a requirement cannot be judged with certainty, the score is held, "
                      'not made up. The evidence per requirement below is still shown.'),
        'hold.p': 'This job could not be fully analyzed, so no score is shown (none was made up).',
        'req.h2': 'Evidence for each requirement',
        'req.meta': 'Quotes from the CV you approved',
        'req.required': 'Required',
        'req.preferred': 'Nice to have · not scored',
        'req.other': 'Other requirement · not scored',
        'req.quoteLabel': 'Quoted from your CV',
        'reason.match': 'This quote shows experience that matches this requirement.',
        'reason.partial': "There's related information, but your context or contribution isn't clear enough yet.",
        'reason.none': "JobFit didn't find evidence of this in your CV. That doesn't mean you lack the skill.",
        'reason.unchecked': "This requirement wasn't checked, so it isn't counted.",
        'reason.unverified': "Can't be confirmed from this CV. It isn't a gap and isn't counted against you.",
        'reason.conflict': 'Conflicts with the work history you confirmed as complete.',
        'excluded': '{n} requirement(s) need checking and are listed but not scored.',
        'soft': 'Soft skills (shown separately, not in the %): {a} with evidence, {b} partial, of {n}.',
        'exp.h3': 'Experience required',
        'exp.conflict': ("This is about your background, not your wording. Rewriting your CV can't add years of "
                         'experience.'),
        'unverified.h3': "Can't be confirmed from this CV",
        'unverified.p': ('Years, location or work-permit requirements this CV does not establish. Not a gap: they were '
                         'not checked against your background.'),
        'calc.summary': 'How is this score calculated?',
        'calc.body': ('Each required item with evidence counts as 1, and partial evidence as 0.5. The total is divided '
                      "by {n} scored required items. Nice-to-haves and items that need checking aren't counted."),
        'calc.note': ('Requirements are read and matched by an AI model, and every quote is re-checked to match your CV '
                      'text exactly.'),
        'side.strong.h3': 'Already backed up',
        'side.strong.empty': 'No requirements with strong evidence yet.',
        'side.gaps.h3': 'Needs clarifying or adding',
        'side.gaps.empty': 'Every required item has evidence.',
        'side.gaps.note': "Missing evidence isn't missing ability.",
        'side.next.h3': 'Next step',
        'side.next.p': 'Clarify experience you really have.',
        'side.next.btn': 'Improve my CV',
        'analysis.empty.h': 'Pick a job first',
        'analysis.empty.p': 'Fit checks start from a job you choose.',
        'page.coach': 'Improve My CV',
        'coach.back': '← Back to fit result',
        'coach.h1': 'Clarify the evidence. Stay honest.',
        'coach.desc': ('Suggestions for {job}. Built only from your CV evidence and your own answers. Nothing is '
                       'invented, and answers never change the score; the score changes only after you update and '
                       're-upload your CV.'),
        'coach.partial.h2': 'Clarify evidence you already have',
        'coach.item.asks': 'This job asks for',
        'coach.item.current': 'Current evidence in your CV',
        'coach.partial.empty': 'No partial evidence to clarify.',
        'coach.missing.h2': 'Possibly missing from your CV',
        'coach.missing.p': "No evidence doesn't mean you've never done it. Answer honestly first.",
        'coach.missing.q': 'Have you actually done this?',
        'coach.missing.empty': 'No required items without evidence.',
        'coach.yes': 'Yes, I have',
        'coach.no': 'Not yet',
        'coach.no.notice': ("That's fine. Don't add this to your CV. If you want to close this gap, look for a relevant "
                            'project or experience and note what you actually did.'),
        'coach.changeAnswer': 'Change answer',
        'coach.form.intro': 'Answer the two required questions (*). Tools and result can stay empty if there are none.',
        'coach.q.what_when': 'Where and when did you do it? *',
        'coach.q.what_when.hint': 'The project or job, and when.',
        'coach.q.own_part': 'Which part did you do yourself? *',
        'coach.q.own_part.hint': 'What you personally did, not the team overall.',
        'coach.q.tools': 'Which tools or methods did you use?',
        'coach.q.tools.hint': "Use the exact names. Don't guess.",
        'coach.q.result': 'What was the result? Is there a number you can back up?',
        'coach.q.result.hint': 'A real outcome. Leave empty if there is none.',
        'coach.form.error': 'Please complete: {list}.',
        'coach.submit': 'Draft from my answers',
        'coach.true.h2': 'True gaps (facts, not wording)',
        'coach.true.note': 'No rewriting advice applies here.',
        'coach.unverified.h2': "Can't be confirmed from this CV",
        'coach.nothing': 'Nothing to improve for this job from the required items.',
        'coach.ideas': 'Ideas you can act on',
        'draft.h4': 'Draft from your answers',
        'draft.note': ("Double-check it's true before adding it to your CV. JobFit doesn't add any tools, numbers or "
                       'experience.'),
        'draft.editLabel': 'Edit draft',
        'draft.save': 'Save',
        'draft.accept': 'Accept',
        'draft.edit': 'Edit',
        'draft.reject': 'Reject',
        'draft.copy': 'Copy the draft (copy icon at the top right of the box)',
        'draft.status.accepted': 'Accepted',
        'draft.status.rejected': 'Rejected',
        'draft.status.edited': 'Edited by you',
        'draft.status.review': 'Needs review',
        'draft.facts': 'Answers used',
        'dialog.accept.title': "Have you checked it's accurate?",
        'dialog.accept.body': ('Make sure every detail is true and something you can explain in an interview. The draft '
                               "is kept in this session only. Your original CV and score don't change."),
        'dialog.accept.yes': 'Yes, save draft',
        'dialog.accept.no': 'Review again',
        'toast.accepted': "Draft saved in this session. Your original CV hasn't changed.",
        'toast.rejected': 'Draft rejected. Your answers are still here if you want to revise them.',
        'market.back': '← Back',
        'market.eyebrow': 'Extra insight',
        'market.h1': 'Most-requested skills',
        'market.desc': "Counted from jobs in JobFit's database. Not a picture of the whole job market.",
        'market.role': 'Role family',
        'market.all': 'All role families',
        'market.row': '{n} of {total} jobs',
        'market.lead': ('In {total} searchable postings, {skill} appears in {n} ({pct}%). Counts come from the skill list '
                        'of each posting, not from the whole job market.'),
        'market.empty': 'No postings match this filter.',
        'market.source': 'Source: {source}',
        'demo.eyebrow': 'Sample CV · saved results',
        'demo.h1': 'Try JobFit with a sample CV',
        'demo.desc': ('Synthetic CVs, not real people. The default mode uses saved results: instant, free and no '
                      'upload.'),
        'demo.cv': 'Choose a sample CV',
        'demo.cv.option': '{id} (synthetic): {jobs}',
        'demo.cv.nojobs': 'no work history',
        'demo.seniority': 'Move jobs asking 3+ years down',
        'demo.seniority.help': 'Early-career rule. Jobs are moved down, never removed.',
        'demo.live': 'Live analysis (paid model calls)',
        'demo.live.help': ('Off: demo with saved results, instant and free, unfiltered list only. On: runs the real '
                           'pipeline now (development only).'),
        'demo.filters': 'Filters (live analysis only)',
        'demo.unknown': 'Also show jobs where this information is missing',
        'demo.unknown.help': 'Missing is not the same as a match. These jobs are shown in their own block.',
        'demo.summary': 'Parsing summary (check before analysis)',
        'demo.summary.location': ('Location suggestion: {loc} (a suggestion only; it is never used as your confirmed '
                                  'location).'),
        'demo.summary.none': 'not found',
        'demo.summary.sections': 'Sections found: {sections}',
        'demo.summary.unavailable': 'Summary not available ({status}).',
        'demo.col.title': 'Title', 'demo.col.org': 'Organization', 'demo.col.start': 'Start', 'demo.col.end': 'End',
        'demo.present': 'present',
        'demo.text': 'Show sample CV text',
        'demo.run': 'Find matching jobs →',
        'demo.saved': 'Demo with saved results: computed earlier for this synthetic CV and this configuration.',
        'demo.analyzed': '{k} candidates from the search were analyzed (stage-1 search, then evidence matching). {rule}',
        'demo.rule.on': '{n} job(s) moved down by the 3+ years rule.',
        'demo.rule.off': 'The 3+ years rule is off.',
        'demo.matches': 'Matches ({n})',
        'demo.conflicts': 'Possible conflict ({n})',
        'demo.conflicts.p': ('These jobs ask for more years than your whole confirmed work history. The score is '
                             'unchanged; they are listed after the other scored jobs.'),
        'demo.unscored': 'Could not be fully analyzed ({n})',
        'demo.suggest.h2': 'CV suggestions',
        'demo.suggest.btn': 'Show suggestions from these results',
        'demo.suggest.none': 'No suggestions: no partly supported or missing required items in the scored jobs.',
        'demo.suggest.asked': 'asked by {n} analyzed job(s)',
        'demo.suggest.quote': 'From your CV: {q}',
        'demo.coach.pick': 'Improve the CV for one demo job',
        'demo.versions': 'Versions: {v}',
        'demo.failed': 'The analysis stopped ({error}). No score was made up.',
        'card.of': '{a} supported, {b} partly, of {n} required',
        'card.evidence': 'Evidence per requirement',
        'card.posting': 'Job posting',
        'card.posting.load': 'Load posting text',
        'card.posting.error': 'Could not load the posting ({err}).',
        'card.conflict': 'Possible conflict: {msg}',
        'card.status.final': 'Score', 'card.status.provisional': 'Provisional score',
        'card.status.on_hold': 'Not fully analyzed', 'card.status.no_score': 'No score',
        'col.requirement': 'Requirement', 'col.type': 'Type', 'col.result': 'Result', 'col.quote': 'CV quote',
        'feedback.reason': 'Reason',
        'feedback.useful': 'Useful', 'feedback.not': 'Not useful',
        'feedback.thanks': 'Thanks, feedback saved (rating and reason only).',
        'reason.relevant': 'Relevant', 'reason.not_relevant_role': 'Wrong role', 'reason.too_senior': 'Too senior',
        'reason.wrong_evidence': 'Evidence is wrong', 'reason.missing_requirement': 'A requirement is missing',
        'reason.other': 'Other',
        'dialog.help.title': 'How to read JobFit results',
        'dialog.help.p1': ('<strong>Find Jobs</strong> shows jobs relevant to your CV. <strong>Analyze Fit</strong> '
                           'compares each requirement with quotes from your CV.'),
        'dialog.help.p2': ("<strong>CV Evidence Coverage</strong> shows how many required items have evidence. It's "
                           "not your chance of getting hired, and it's not an ATS score."),
        'dialog.help.p3': ("Missing evidence doesn't mean you lack the skill. Anything JobFit can't confirm is marked "
                           "<strong>Can't confirm yet</strong>."),
        'dialog.help.small': ('Limited beta: {limit} fit checks per session. Your file is processed briefly on the server, '
                              'cleaned of personal details, and sent to AI services through OpenRouter only after you '
                              'agree. Session data is deleted when you press Delete session, about 2 minutes after you '
                              'close the page, after 30 minutes without activity, or after 2 hours.'),
        'dialog.delete.title': 'Stop & delete this session?',
        'dialog.delete.body': ('Your CV text, approval, fit results, job descriptions and drafts in this session will be '
                               'deleted on the server. Anything running will stop.'),
        'dialog.delete.small': "This can't be undone. The original file on your device isn't affected.",
        'dialog.delete.yes': 'Stop & delete session',
        'dialog.replace.title': 'Replace this CV?',
        'dialog.replace.body': ('Your approval, results, work-history answer and drafts for this CV will be deleted. Fit '
                                "checks you've already used still count."),
        'limit.title': "You've used all fit checks",
        'limit.body': "You've used {limit} fit checks in this session. You can still open your existing results.",
        'deleted.h1': 'Session deleted',
        'deleted.desc': 'Your session data was cleared on the server.',
        'expired.h1': 'Your session has ended',
        'expired.desc': ('The session ended (no activity, or the page was away too long) and its data was deleted on '
                         'the server. A new empty session has started.'),
        'terminal.h2': "You're still in control.",
        'terminal.p.deleted': 'You can start again anytime with the same CV or a new one.',
        'terminal.p.expired': "Old sessions aren't restored. Upload your CV again and re-approve the text.",
        'terminal.btn': 'Back to home',
        'api.down.h1': "JobFit can't be reached yet",
        'api.down.p': ('Cannot reach the JobFit API at {url}. It may still be starting. Wait a few seconds and press '
                       'Retry. ({err})'),
        'api.retry': 'Retry',
        'api.outdated': ('<strong>The connected API ({url}) is an old version.</strong> It does not apply the D-104 '
                         'cleanup: the name and contact header are not removed, and editing the text is not '
                         'supported. Run the UI against the current API (see the owner-local runbook), then reload.'),
        'err.not_found': ('The API at {url} does not know this step (Not Found). It is probably an old version; run the '
                          'API from the current code.'),
        'err.connection': ('Connection problem: press the button again to retry the same request (it will not run '
                           'twice).'),
        'err.stopped': 'Stopped ({error}). No result was made up.',
        'err.code.allowance_exhausted': "This session's allowance for this step is used up.",
        'err.code.busy': 'Another request is being processed. Please try again in a moment.',
        'err.code.consent_required': 'Approval for this CV text is missing or no longer valid.',
        'err.code.search_required': 'Run Find Jobs first.',
        'err.code.parse_required': 'Your CV is not prepared yet. Approve the text and continue first.',
        'err.code.input_too_large': 'The text is too long to analyze in this beta.',
        'err.code.ticket_required': 'Live analysis is not available for this session.',
        'err.code.unavailable': 'Live AI analysis is temporarily unavailable. Please try again later. No score was created.',
        'err.code.production_retrieval_unavailable': 'Search is unavailable right now. Your CV is still ready.',
    },
}


def lang() -> str:
    value = st.session_state.get('lang', 'id')
    return value if value in LANGS else 'id'


def t(key: str, **values) -> str:
    """The copy for ``key`` in the current language; ``{name}`` placeholders are filled from ``values``.

    Values are inserted as given: callers escape untrusted text before it reaches HTML.
    """
    text = COPY[lang()].get(key)
    if text is None:
        text = COPY['id'][key]                  # a missing key fails loudly in tests (KeyError)
    for name, value in values.items():
        text = text.replace('{' + name + '}', str(value))
    return text


# Fixed sentences the API returns in English (jobfit.support.cv_coach); shown in Indonesian when the
# interface is Indonesian. Anything else from the API is shown unchanged.
_API_ID = {
    ('If accurate, make this line more specific: what you did, which tool or method, and the result. Name a tool or '
     'skill only if you actually used it.'):
        ('Kalau memang begitu, buat baris ini lebih spesifik: apa yang kamu kerjakan, alat atau metode apa, dan '
         'hasilnya. Sebut alat atau keterampilan hanya kalau kamu benar-benar memakainya.'),
    "A fact about your background, not wording; changing the CV cannot fix it.":
        'Fakta tentang latar belakang kamu, bukan soal kata-kata; mengubah CV tidak bisa memperbaikinya.',
    'Not verified from this CV.': 'Belum bisa dipastikan dari CV ini.',
    'Build a small project that uses it, then describe that project on your CV.':
        'Bangun proyek kecil yang memakainya, lalu jelaskan proyek itu di CV kamu.',
    'Run the matching again after you update your CV; answers never change the score.':
        'Jalankan pencocokan lagi setelah CV kamu diperbarui; jawaban tidak pernah mengubah skor.',
    'Built only from your answers. Check it, then accept, edit, reject or copy it.':
        'Disusun hanya dari jawaban kamu. Cek dulu, lalu terima, edit, tolak, atau salin.',
}
_API_ID_PREFIX = {'Learn the basics of: ': 'Pelajari dasar-dasar: '}


def api_text(text: str) -> str:
    """A fixed API sentence in the interface language (untranslated when unknown)."""
    text = str(text or '')
    if lang() != 'id':
        return text
    if text in _API_ID:
        return _API_ID[text]
    for prefix, local in _API_ID_PREFIX.items():
        if text.startswith(prefix):
            return local + text[len(prefix):]
    return text
